#!/bin/sh
# KenLens broker entrypoint — Story 10.3 (spec D7).
#
# Writes the Mosquitto config at every container start, then hands over to the image's
# own entrypoint. Generating it here rather than on the host means toggling
# MQTT_ANONYMOUS_LISTENER is an `.env` edit and `docker compose up -d`, nothing more.
#
#   8883  always: TLS, username + password, no anonymous access.
#   1883  only with MQTT_ANONYMOUS_LISTENER=true: anonymous, plain TCP. Insecure, and here
#         only because today's anchor firmware can do nothing else
#         (asgard/uwbfirmware-anchor#78). Off, compose still publishes 1883 but no listener
#         is behind it, so a client is refused.
set -eu

conf=/tmp/mosquitto.conf

cat > "$conf" <<'EOF'
# Generated by /kenlens/start.sh at container start — edits here are lost on restart.
per_listener_settings true

persistence true
persistence_location /mosquitto/data/

log_dest stdout
log_type error
log_type warning
log_type notice
log_type information

listener 8883 0.0.0.0
allow_anonymous false
password_file /kenlens/passwd
certfile /kenlens/tls/mqtt-broker.crt
keyfile /kenlens/tls/mqtt-broker.key
tls_version tlsv1.2
EOF

case "${MQTT_ANONYMOUS_LISTENER:-false}" in
  true)
    echo "kenlens: MQTT_ANONYMOUS_LISTENER=true - serving anonymous plain-TCP MQTT on 1883 (insecure)" >&2
    cat >> "$conf" <<'EOF'

# MQTT_ANONYMOUS_LISTENER=true — anonymous, unencrypted. For anchor firmware that cannot
# do TLS yet; turn it off once the fleet is on 8883.
listener 1883 0.0.0.0
allow_anonymous true
EOF
    ;;
  false) ;;
  *)
    echo "kenlens: MQTT_ANONYMOUS_LISTENER must be 'true' or 'false', got '${MQTT_ANONYMOUS_LISTENER}'" >&2
    exit 1
    ;;
esac

exec /docker-entrypoint.sh /usr/sbin/mosquitto -c "$conf"
