#!/bin/sh
# KenLens broker entrypoint.
#
# Writes the Mosquitto config at every container start, then hands over to the image's
# own entrypoint. Two listeners, both always open at the socket level:
#
#   8883  TLS, username + password, never anonymous. Its users live in Mosquitto's
#         dynamic-security plugin (dynamic-security.json in the data volume), and KenLens
#         manages them: its own server user and the anchor credentials an admin adds on the
#         MQTT settings page. Nothing here writes a user except the plugin's admin.
#   1883  plain TCP, no users. Anonymous clients are accepted only while the anonymous
#         listener is on — insecure, and there only because today's anchor firmware can do
#         nothing else. An ACL keeps them to the anchor topics.
#
# Whether 1883 accepts anonymous clients is read from the control file KenLens writes
# (/kenlens/control/anonymous-listener, "true" or "false") and, until KenLens has written
# it, from MQTT_ANONYMOUS_LISTENER. A watcher polls the file and, when it changes,
# rewrites the config and sends SIGHUP: Mosquitto re-reads allow_anonymous live, with no
# restart, and drops anonymous sessions when it is switched off. Listeners themselves
# cannot change on a reload, which is why 1883 always exists.
set -eu

conf=/tmp/mosquitto.conf
acl=/tmp/anonymous.acl
dynsec=/mosquitto/data/dynamic-security.json
control=/kenlens/control/anonymous-listener
# The plugin's admin. KenLens logs in as this user (Mqtt:Embedded:AdminUsername) to manage
# the other users; keep the two in step.
admin_user=kenlens-broker-admin
admin_password_file=/kenlens/mqtt-admin-password

# The ACL is written from these rather than hard-coded, because a fleet may carry another
# prefix. They must match the server's UwbConfig:EventTopicPrefix, UwbConfig:JobTopicRoot and
# AnchorConsole:CertTopicRoot.
anchor_prefix=${MQTT_ANCHOR_TOPIC_PREFIX:-uwb/anchor}
job_root=${MQTT_JOB_TOPIC_ROOT:-kenlens/cfg/job}
console_cert_root=${MQTT_CONSOLE_CERT_TOPIC_ROOT:-kenlens/console/cert}

die() { echo "kenlens: $*" >&2; exit 1; }

is_bool() { [ "$1" = true ] || [ "$1" = false ]; }

is_topic_root() { # a literal topic root: no wildcard, no space, no leading or trailing /
  case "$1" in
    '' | *'#'* | *'+'* | *' '* | /* | */) return 1 ;;
  esac
}

default_anonymous=${MQTT_ANONYMOUS_LISTENER:-false}
is_bool "$default_anonymous" \
  || die "MQTT_ANONYMOUS_LISTENER must be 'true' or 'false', got '$default_anonymous'"
is_topic_root "$anchor_prefix" || die "MQTT_ANCHOR_TOPIC_PREFIX '$anchor_prefix' is not a literal topic root"
is_topic_root "$job_root" || die "MQTT_JOB_TOPIC_ROOT '$job_root' is not a literal topic root"
is_topic_root "$console_cert_root" \
  || die "MQTT_CONSOLE_CERT_TOPIC_ROOT '$console_cert_root' is not a literal topic root"

# The requested state: the control file once KenLens has written one, else the environment.
# A file holding anything but true/false is ignored (and reported by the watcher).
requested() {
  if [ -f "$control" ]; then
    value=$(tr -d ' \r\n' < "$control" 2>/dev/null || true)
    if is_bool "$value"; then echo "$value"; return; fi
    echo invalid
    return
  fi
  echo "$default_anonymous"
}

write_conf() { # write_conf <true|false> — replaced whole, so a reload never reads half a file
  cat > "$conf.tmp" <<EOF
# Generated by /kenlens/start.sh — edits here are lost on the next change or restart.
per_listener_settings true

persistence true
persistence_location /mosquitto/data/

log_dest stdout
log_type error
log_type warning
log_type notice
log_type information

listener 8883 0.0.0.0
allow_anonymous false
certfile /kenlens/tls/mqtt-broker.crt
keyfile /kenlens/tls/mqtt-broker.key
tls_version tlsv1.2
plugin /usr/lib/mosquitto_dynamic_security.so
plugin_opt_config_file $dynsec

# Anonymous, unencrypted. Accepts clients only while the anonymous listener is on; the ACL
# holds them to the anchor topics, and keeps them from reading the plugin's \$CONTROL
# responses, which name every user.
listener 1883 0.0.0.0
allow_anonymous $1
acl_file $acl
EOF
  chmod 0644 "$conf.tmp"
  mv -f "$conf.tmp" "$conf"
}

# Topic lines before any `user` line apply to anonymous clients — the only kind on 1883.
# An anchor publishes under its prefix and subscribes to its own job topic and to its console
# certificate (issue #234) — the latter by client id, which the anchor sets to its board id.
cat > "$acl" <<EOF
topic write $anchor_prefix/#
topic read $job_root/#
pattern read $console_cert_root/%c
EOF
chmod 0644 "$acl"

# First start of this data volume: create the plugin's store with its admin, the one
# operation the plugin can do offline. KenLens creates every other user when it starts.
if [ ! -f "$dynsec" ]; then
  [ -s "$admin_password_file" ] \
    || die "$admin_password_file is missing or empty — run kenlens-setup.sh to create config/secrets/mqtt-admin-password"
  mosquitto_ctrl dynsec init "$dynsec" "$admin_user" "$(cat "$admin_password_file")" >/dev/null \
    || die "could not initialise $dynsec"
  echo "kenlens: created the broker's user store with its admin; KenLens adds the other users" >&2
fi

current=$(requested)
[ "$current" = invalid ] && current=$default_anonymous
write_conf "$current"
[ "$current" = true ] \
  && echo "kenlens: anonymous plain-TCP MQTT on 1883 is ON (insecure)" >&2

# After the exec below this shell's PID is Mosquitto's, which is where SIGHUP goes.
broker=$$
(
  reported=""
  while sleep 2; do
    want=$(requested)
    if [ "$want" = invalid ]; then
      [ "$reported" = invalid ] || echo "kenlens: $control holds neither true nor false; ignored" >&2
      reported=invalid
      continue
    fi
    reported=""
    [ "$want" = "$current" ] && continue
    write_conf "$want"
    current=$want
    echo "kenlens: anonymous listener on 1883 -> $want; reloading the broker" >&2
    kill -HUP "$broker"
  done
) &

exec /docker-entrypoint.sh /usr/sbin/mosquitto -c "$conf"
